In [1]:
import pandas as pd

In [2]:
reduction2016 = pd.read_csv("../DB/Data/2016_-_Cities_Emissions_Reduction_Targets_20240207.csv")
reduction2017 = pd.read_csv("../DB/Data/2017_-_Cities_Emissions_Reduction_Targets_20240207.csv")
emission2016 = pd.read_csv("../DB/Data/2016_-_Citywide_GHG_Emissions_20240207.csv")
emission2017 = pd.read_csv("../DB/Data/2017_-_Cities_Community_Wide_Emissions.csv")
report2023 = pd.read_csv("../DB/Data/2023_Cities_Climate_Risk_and_Vulnerability_Assessments_20240207.csv")

In [3]:
def check_null(df):
    # Check for null values in each column
    null_counts = df.isnull().sum()

    # Print columns with null values
    print("Columns with null values:")
    print(null_counts[null_counts > 0])

In [4]:
# Function to convert C40 to True and NaN to False
def convert_to_boolean(value):
    if value == 'C40':
        return True
    else:
        return False

## Reduction 2016

In [5]:
reduction2016

,Organisation,Account No,Country,City Short Name,C40,Reporting Year,Sector,Target boundary,Baseline year,Baseline emissions (metric tonnes CO2e),Percentage reduction target,Target date,Comment,City Location,Country Location
0,Odder Kommune,58796,Denmark,Odder Kommune,NaN,2016,Total,NaN,2010,6136.00,2.0,NaN,NaN,"(55.975718, 10.149958)","(56.26392, 9.501785)"
1,Comune di Napoli,36158,Italy,Napoli,NaN,2016,Total,NaN,2005,2913434.00,25.0,2020.0,NaN,"(40.8419943, 14.2513831)","(41.87194, 12.56738)"
2,Egedal Municipality,62855,Denmark,Egedal Municipality,NaN,2016,Total,NaN,2009,268000.00,7.0,2020.0,The municipality are increasing in terms of ci...,"(55.795045, 12.238733)","(56.26392, 9.501785)"
3,Yilan County,61753,Taiwan,Yilan,NaN,2016,Total,NaN,2009,3804493.00,35.0,2020.0,NaN,"(24.702107, 121.73775)","(23.69781, 120.960515)"
4,"City of Emeryville, CA",61790,USA,"Emeryville, CA",NaN,2016,Total,Overall community emissions,2004,178832.00,40.0,2030.0,NaN,"(37.831316, -122.285247)","(37.09024, -95.712891)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
275,Ville de Salaberry-de-Valleyfield,60680,Canada,Salaberry-de-Valleyfield,NaN,2016,Total,Community sector:\n- Waste management\n- road ...,2009,198408.23,20.0,2020.0,NaN,"(45.250091, -74.133086)","(56.130366, -106.346771)"
276,Moscow Government,31174,Russia,Moscow,C40,2016,Total,Total emissions within the inventory boundary,1990,63443619.00,25.0,2020.0,NaN,"(55.755826, 37.6173)","(61.52401, 105.318756)"
277,Stadt Heidelberg,31165,Germany,Stadt Heidelberg,C40,2016,Total,NaN,1990,NaN,95.0,2050.0,NaN,"(49.398752, 8.672434)","(51.165691, 10.451526)"
278,"City of Davis, CA",59552,USA,"Davis, CA",NaN,2016,Total,Municipal boundary/city limits,2010,348437.00,100.0,2050.0,NaN,"(38.544907, -121.740517)","(37.09024, -95.712891)"
279,City of Hiroshima,49386,Japan,Hiroshima,NaN,2016,Total,CO2\nCH4\nNO2\nHFCs,1990,8525221.00,6.0,NaN,NaN,"(34.385203, 132.455293)","(36.204824, 138.252924)"

In [22]:
check_null(reduction2016)

Columns with null values:
C40                                        197
Sector                                      12
Target boundary                             58
Baseline year                                5
Baseline emissions (metric tonnes CO2e)     18
Target date                                 10
Comment                                    142
dtype: int64

In [38]:
reduction2016.rename(columns={'City Short Name': 'City Name'}, inplace=True)
reduction2016['C40'] = reduction2016['C40'].apply(lambda x: convert_to_boolean(x))

reduction2016.drop(columns=['Organisation'], inplace=True)

reduction2016.head()

,Account No,Country,City Name,C40,Reporting Year,Sector,Target boundary,Baseline year,Baseline emissions (metric tonnes CO2e),Percentage reduction target,Target date,Comment,City Location,Country Location
0,58796,Denmark,Odder Kommune,False,2016,Total,NaN,2010,6136.0,2.0,NaN,NaN,"(55.975718, 10.149958)","(56.26392, 9.501785)"
1,36158,Italy,Napoli,False,2016,Total,NaN,2005,2913434.0,25.0,2020.0,NaN,"(40.8419943, 14.2513831)","(41.87194, 12.56738)"
2,62855,Denmark,Egedal Municipality,False,2016,Total,NaN,2009,268000.0,7.0,2020.0,The municipality are increasing in terms of ci...,"(55.795045, 12.238733)","(56.26392, 9.501785)"
3,61753,Taiwan,Yilan,False,2016,Total,NaN,2009,3804493.0,35.0,2020.0,NaN,"(24.702107, 121.73775)","(23.69781, 120.960515)"
4,61790,USA,"Emeryville, CA",False,2016,Total,Overall community emissions,2004,178832.0,40.0,2030.0,NaN,"(37.831316, -122.285247)","(37.09024, -95.712891)"

In [45]:
# Save the DataFrame to a CSV file
reduction2016.to_csv('../DB/Data/new_2016_reductions.csv', index=False)

## Reduction 2017

In [28]:
reduction2017

,Account No,Organisation,City,Country,Region,Access,C40,Reporting year,Type of target,Sector,...,Baseline emissions (metric tonnes CO2e),Percentage reduction target,Target date,Estimated business as usual absolute emissions in target year (metric tonnes CO2e),​Intensity unit (emissions per),Comment,Population,Population Year,City Location,Country Location
0,54408,Aarhus Kommune,Aarhus,Denmark,Europe,Public,NaN,2017,Absolute target,NaN,...,NaN,100.0,2030,NaN,NaN,NaN,336000.0,2017.0,"(56.168393, 10.137373)","(56.26392, 9.501785)"
1,63616,Abasan Al-Kabira Municipality,Abasan Al-Kabira,State of Palestine,South and West Asia,Public,NaN,2017,Absolute target,Buildings,...,18320.0,19.0,2020,NaN,NaN,NaN,30000.0,2015.0,"(31.323126, 34.344025)","(31.9522, 35.2332)"
2,63616,Abasan Al-Kabira Municipality,Abasan Al-Kabira,State of Palestine,South and West Asia,Public,NaN,2017,Absolute target,Transport,...,6893.0,6.0,2020,NaN,NaN,NaN,30000.0,2015.0,"(31.323126, 34.344025)","(31.9522, 35.2332)"
3,1499,Ajuntament de Barcelona,Barcelona,Spain,Europe,Public,C40,2017,Absolute target,Total,...,4053.0,18.0,2020,NaN,NaN,NaN,1608746.0,2016.0,"(41.382271, 2.177506)","(40.463667, -3.74922)"
4,1499,Ajuntament de Barcelona,Barcelona,Spain,Europe,Public,C40,2017,Absolute target,Buildings,...,2164.0,1.0,2020,NaN,NaN,"Residential, Commercial and Industrial",1608746.0,2016.0,"(41.382271, 2.177506)","(40.463667, -3.74922)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,43937,Wellington City Council,Wellington,New Zealand,South Asia and Oceania,Public,NaN,2017,Absolute target,Total,...,1105654.0,40.0,2030,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
402,43937,Wellington City Council,Wellington,New Zealand,South Asia and Oceania,Public,NaN,2017,Absolute target,Total,...,1105654.0,65.0,2040,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
403,43937,Wellington City Council,Wellington,New Zealand,South Asia and Oceania,Public,NaN,2017,Absolute target,Total,...,1105654.0,80.0,2050,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
404,43937,Wellington City Council,Wellington,New Zealand,South Asia and Oceania,Public,NaN,2017,Absolute target,Other: Corporate,...,92832.0,80.0,2050,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
405,69835,Municipalidad de Yala,Yala,Argentina,Latin America,Public,NaN,2017,Absolute target,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4811.0,2011.0,"43 130026\n(41.112598, -112.051762)","(-38.416097, -63.616672)"

In [23]:
check_null(reduction2017)

Columns with null values:
City                                                                                    2
Country                                                                                 2
Region                                                                                  2
C40                                                                                   312
Sector                                                                                108
Baseline year                                                                          34
Baseline emissions (metric tonnes CO2e)                                               132
Percentage reduction target                                                            74
Target date                                                                            56
Estimated business as usual absolute emissions in target year (metric tonnes CO2e)    375
​Intensity unit (emissions per)                                                       383
Comment                                                                               266
Population                                                                              2
Population Year                                                                         2
City Location                                                                           2
Country Location                                                                        2
dtype: int64

In [39]:
reduction2017['C40'] = reduction2017['C40'].apply(lambda x: convert_to_boolean(x))
reduction2017.drop(columns=['Organisation'], inplace=True)

reduction2017

,Account No,City,Country,Region,Access,C40,Reporting year,Type of target,Sector,Baseline year,Baseline emissions (metric tonnes CO2e),Percentage reduction target,Target date,Estimated business as usual absolute emissions in target year (metric tonnes CO2e),​Intensity unit (emissions per),Comment,Population,Population Year,City Location,Country Location
0,54408,Aarhus,Denmark,Europe,Public,False,2017,Absolute target,NaN,2008,NaN,100.0,2030,NaN,NaN,NaN,336000.0,2017.0,"(56.168393, 10.137373)","(56.26392, 9.501785)"
1,63616,Abasan Al-Kabira,State of Palestine,South and West Asia,Public,False,2017,Absolute target,Buildings,2010,18320.0,19.0,2020,NaN,NaN,NaN,30000.0,2015.0,"(31.323126, 34.344025)","(31.9522, 35.2332)"
2,63616,Abasan Al-Kabira,State of Palestine,South and West Asia,Public,False,2017,Absolute target,Transport,2010,6893.0,6.0,2020,NaN,NaN,NaN,30000.0,2015.0,"(31.323126, 34.344025)","(31.9522, 35.2332)"
3,1499,Barcelona,Spain,Europe,Public,False,2017,Absolute target,Total,2008,4053.0,18.0,2020,NaN,NaN,NaN,1608746.0,2016.0,"(41.382271, 2.177506)","(40.463667, -3.74922)"
4,1499,Barcelona,Spain,Europe,Public,False,2017,Absolute target,Buildings,2008,2164.0,1.0,2020,NaN,NaN,"Residential, Commercial and Industrial",1608746.0,2016.0,"(41.382271, 2.177506)","(40.463667, -3.74922)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
401,43937,Wellington,New Zealand,South Asia and Oceania,Public,False,2017,Absolute target,Total,2001,1105654.0,40.0,2030,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
402,43937,Wellington,New Zealand,South Asia and Oceania,Public,False,2017,Absolute target,Total,2001,1105654.0,65.0,2040,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
403,43937,Wellington,New Zealand,South Asia and Oceania,Public,False,2017,Absolute target,Total,2001,1105654.0,80.0,2050,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
404,43937,Wellington,New Zealand,South Asia and Oceania,Public,False,2017,Absolute target,Other: Corporate,2014,92832.0,80.0,2050,NaN,NaN,NaN,209102.0,2017.0,"(26.661763, -80.268357)","(-40.900557, 174.885971)"
405,69835,Yala,Argentina,Latin America,Public,False,2017,Absolute target,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4811.0,2011.0,"43 130026\n(41.112598, -112.051762)","(-38.416097, -63.616672)"

In [46]:
# Save the DataFrame to a CSV file
reduction2017.to_csv('../DB/Data/new_2017_reductions.csv', index=False)

## Emission 2016

In [27]:
emission2016

,Account Number,City Name,Country,City Short Name,C40,Reporting Year,Measurement Year,Boundary,Primary Methodology,Methodology Details,...,Current Population,City GDP,GDP Currency,Year of GDP,GDP Source,Average annual temperature (in Celsius)​,​Land area (in square km),Average altitude (m),City Location,Country Location
0,35894,Ville de Montreal,Canada,Montreal,NaN,2016,12/31/2009 12:00:00 AM,Other: The regional entity that constitutes th...,2006 IPCC Guidelines for National Greenhouse G...,2006 IPCC Guidelines for National Greenhouse G...,...,1886481.0,1.201180e+11,CAD Canadian Dollar,2014.0,"Ville de Montréal, Montréal en statistiques, h...",6.8,500.0,17.0,"(45.5086699, -73.5539925)","(56.130366, -106.346771)"
1,35898,Greater Manchester,United Kingdom,Manchester,NaN,2016,12/31/2013 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,A GPC Compliant dataset has been established f...,...,2762000.0,8.777300e+10,NaN,2013.0,UK ONS (using 1.56 USD/GBP) Figures provided i...,9.5,1277.0,250.0,"(53.4575955, -2.1578377)","(55.378051, -3.435973)"
2,54128,City of Reno,USA,Reno,NaN,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,Global Protocol for Community-Scale Greenhouse...,Also utilized the U.S. Community Protocol for ...,...,236995.0,1.000000e+10,USD US Dollar,2014.0,Bureau of Economic Analysis10.4,10.4,288.0,1373.0,"(39.5296, -119.8138)","(37.09024, -95.712891)"
3,35879,City of Minneapolis,USA,Minneapolis,NaN,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,U.S. Community Protocol for Accounting and Rep...,A note regarding how double counting is avoide...,...,407207.0,2.357000e+11,USD US Dollar,2014.0,http://www.bea.gov/iTable/iTable.cfm?reqid=70&...,7.9,139.8,264.0,"(44.983334, -93.26667)","(37.09024, -95.712891)"
4,50558,"City of London, ON",Canada,"London, ON",NaN,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,International Emissions Analysis Protocol (ICLEI),as adapted by ICLEI Canada for use in the FCM'...,...,375000.0,1.540000e+10,CAD Canadian Dollar,2014.0,"Conference Board of Canada, London Census Metr...",7.9,421.0,251.0,"(42.9837, -81.2497)","(56.130366, -106.346771)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,59165,Gladsaxe Kommune,Denmark,Gladsaxe Kommune,NaN,2016,12/31/2014 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,NaN,...,66656.0,3.523400e+07,DKK Danish Krone,2014.0,Statistic Denmark,NaN,24.9,NaN,"(55.733461, 12.488686)","(56.26392, 9.501785)"
183,31108,City of Houston,USA,Houston,C40,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,U.S. Community Protocol for Accounting and Rep...,NaN,...,2195914.0,5.174000e+11,USD US Dollar,2014.0,https://www.houston.org/pdf/research/quickview...,21.0,1625.0,13.0,"(29.7601927, -95.3693896)","(37.09024, -95.712891)"
184,31167,City of Lagos,Nigeria,Lagos,C40,2016,12/31/2014 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,NaN,...,21000000.0,1.366000e+12,USD US Dollar,2016.0,www.lagosstate.gov.ng,30.0,3577.0,34.0,"(6.524379, 3.379206)","(9.081999, 8.675277)"
185,54088,City of Peterborough,Canada,Peterborough,NaN,2016,12/31/2011 12:00:00 AM,A metropolitan area,International Emissions Analysis Protocol (ICLEI),NaN,...,78698.0,NaN,NaN,NaN,NaN,12.1,63.8,195.0,"(44.309058, -78.319747)","(56.130366, -106.346771)"
186,42178,Distrito Metropolitano de Quito,Ecuador,Distrito Metropolitano de Quito,C40,2016,12/31/2011 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,NaN,...,2239191.0,1.510000e+10,USD US Dollar,2012.0,Ecuador Central Bank,22.0,4232.0,2815.0,"(-0.2333, -78.5167)","(-1.831239, -78.183406)"

In [24]:
check_null(emission2016)

Columns with null values:
C40                                             133
Methodology Details                              54
Gases included                                    6
Total Scope 1 Emissions (metric tonnes CO2e)     53
Total Scope 2 Emissions (metric tonnes CO2e)     55
Increase/Decrease from last year                 21
Reason for increase/decrease in emissions        43
Current Population                                2
City GDP                                         57
GDP Currency                                     64
Year of GDP                                      50
GDP Source                                       57
Average annual temperature (in Celsius)​         10
​Land area (in square km)                         3
Average altitude (m)                             19
dtype: int64

In [40]:
emission2016['C40'] = emission2016['C40'].apply(lambda x: convert_to_boolean(x))

emission2016

,Account Number,City Name,Country,City Short Name,C40,Reporting Year,Measurement Year,Boundary,Primary Methodology,Methodology Details,...,Current Population,City GDP,GDP Currency,Year of GDP,GDP Source,Average annual temperature (in Celsius)​,​Land area (in square km),Average altitude (m),City Location,Country Location
0,35894,Ville de Montreal,Canada,Montreal,False,2016,12/31/2009 12:00:00 AM,Other: The regional entity that constitutes th...,2006 IPCC Guidelines for National Greenhouse G...,2006 IPCC Guidelines for National Greenhouse G...,...,1886481.0,1.201180e+11,CAD Canadian Dollar,2014.0,"Ville de Montréal, Montréal en statistiques, h...",6.8,500.0,17.0,"(45.5086699, -73.5539925)","(56.130366, -106.346771)"
1,35898,Greater Manchester,United Kingdom,Manchester,False,2016,12/31/2013 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,A GPC Compliant dataset has been established f...,...,2762000.0,8.777300e+10,NaN,2013.0,UK ONS (using 1.56 USD/GBP) Figures provided i...,9.5,1277.0,250.0,"(53.4575955, -2.1578377)","(55.378051, -3.435973)"
2,54128,City of Reno,USA,Reno,False,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,Global Protocol for Community-Scale Greenhouse...,Also utilized the U.S. Community Protocol for ...,...,236995.0,1.000000e+10,USD US Dollar,2014.0,Bureau of Economic Analysis10.4,10.4,288.0,1373.0,"(39.5296, -119.8138)","(37.09024, -95.712891)"
3,35879,City of Minneapolis,USA,Minneapolis,False,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,U.S. Community Protocol for Accounting and Rep...,A note regarding how double counting is avoide...,...,407207.0,2.357000e+11,USD US Dollar,2014.0,http://www.bea.gov/iTable/iTable.cfm?reqid=70&...,7.9,139.8,264.0,"(44.983334, -93.26667)","(37.09024, -95.712891)"
4,50558,"City of London, ON",Canada,"London, ON",False,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,International Emissions Analysis Protocol (ICLEI),as adapted by ICLEI Canada for use in the FCM'...,...,375000.0,1.540000e+10,CAD Canadian Dollar,2014.0,"Conference Board of Canada, London Census Metr...",7.9,421.0,251.0,"(42.9837, -81.2497)","(56.130366, -106.346771)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,59165,Gladsaxe Kommune,Denmark,Gladsaxe Kommune,False,2016,12/31/2014 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,NaN,...,66656.0,3.523400e+07,DKK Danish Krone,2014.0,Statistic Denmark,NaN,24.9,NaN,"(55.733461, 12.488686)","(56.26392, 9.501785)"
183,31108,City of Houston,USA,Houston,False,2016,12/31/2014 12:00:00 AM,Administrative boundary of a local government,U.S. Community Protocol for Accounting and Rep...,NaN,...,2195914.0,5.174000e+11,USD US Dollar,2014.0,https://www.houston.org/pdf/research/quickview...,21.0,1625.0,13.0,"(29.7601927, -95.3693896)","(37.09024, -95.712891)"
184,31167,City of Lagos,Nigeria,Lagos,False,2016,12/31/2014 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,NaN,...,21000000.0,1.366000e+12,USD US Dollar,2016.0,www.lagosstate.gov.ng,30.0,3577.0,34.0,"(6.524379, 3.379206)","(9.081999, 8.675277)"
185,54088,City of Peterborough,Canada,Peterborough,False,2016,12/31/2011 12:00:00 AM,A metropolitan area,International Emissions Analysis Protocol (ICLEI),NaN,...,78698.0,NaN,NaN,NaN,NaN,12.1,63.8,195.0,"(44.309058, -78.319747)","(56.130366, -106.346771)"
186,42178,Distrito Metropolitano de Quito,Ecuador,Distrito Metropolitano de Quito,False,2016,12/31/2011 12:00:00 AM,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,NaN,...,2239191.0,1.510000e+10,USD US Dollar,2012.0,Ecuador Central Bank,22.0,4232.0,2815.0,"(-0.2333, -78.5167)","(-1.831239, -78.183406)"

In [47]:
# Save the DataFrame to a CSV file
emission2016.to_csv('../DB/Data/new_2016_emissions.csv', index=False)

## Emission 2017

In [26]:
emission2017

,Account number,Organization,City,Country,Region,C40,Access,Reporting year,Accounting year,Boundary,...,Population year,GDP,GDP Currency,GDP Year,GDP Source,Average annual temperature (in Celsius)​,​Average altitude (m),​Land area (in square km),City Location,Country Location
0,49363,Nelson Mandela Bay Municipality,Nelson Mandela Bay,South Africa,Africa,NaN,Public,2017,2013-07-01 - 2014-06-30,A metropolitan area,...,2011,5.214700e+04,ZAR South African Rand,2010.0,Built Environment Performance Plan(BEPP),17.5,69.0,1950.0,"(-33.745241, 25.568108)","(-30.559482, 22.937506)"
1,31171,Ayuntamiento de Madrid,Madrid,Spain,Europe,C40,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,...,2016,1.293780e+11,EUR Euro,2015.0,Contabilidad Municipal Trimestral. Ciudad de M...,15.0,655.0,604.0,"(40.1076253, -3.3875673)","(40.463667, -3.74922)"
2,3417,New York City,New York City,USA,North America,C40,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,...,2016,1.558520e+12,USD US Dollar,2015.0,http://www.brookings.edu/research/reports2/201...,13.0,10.0,784.0,"(40.7127837, -74.0059413)","(37.09024, -95.712891)"
3,59537,"City of Denton, TX","Denton, TX",USA,North America,NaN,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,...,2015,NaN,NaN,NaN,NaN,18.2,192.0,227.8,"(33.214841, -97.133068)","(37.09024, -95.712891)"
4,35894,Ville de Montreal,Montreal,Canada,North America,C40,Public,2017,2013-01-01 - 2013-12-31,A metropolitan area,...,2013,1.154128e+08,CAD Canadian Dollar,2013.0,Institut de la statistique du Québec,6.8,17.0,500.0,"(45.5086699, -73.5539925)","(56.130366, -106.346771)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,19233,Torres Vedras Municipality,Torres Vedras,Portugal,Europe,NaN,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,...,2011,NaN,NaN,NaN,NaN,15.0,75.0,407.0,"(38.763669, -9.30148)","(39.399872, -8.224454)"
225,60273,Prefeitura de Extrema,Extrema,Brazil,Latin America,NaN,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,...,2016,4.676285e+09,BRL Brazilian Real,2014.0,IBGE,17.7,973.0,243.1,"(-22.840262, -46.328)","(-14.235004, -51.92528)"
226,31148,City of Amsterdam,Amsterdam,Netherlands,Europe,C40,Public,2017,2015-12-01 - 2016-12-31,Administrative boundary of a local government,...,2016,6.450000e+10,EUR Euro,2016.0,https://public.tableau.com/profile/gemeente.am...,10.9,2.0,219.0,"(52.370216, 4.895168)","(52.132633, 5.291266)"
227,54119,City of Palo Alto,Palo Alto,USA,North America,NaN,Public,2017,2016-01-01 - 2016-12-31,Administrative boundary of a local government,...,2017,NaN,USD US Dollar,NaN,City GDP data is not available,15.0,7.0,67.0,"(37.4419, -122.143)","(37.09024, -95.712891)"
228,35859,City of Cleveland,Cleveland,USA,North America,NaN,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,...,2010,1.284480e+11,USD US Dollar,2015.0,U.S. Bureau of Economic Analysis; U.S. Bureau ...,10.4,199.0,201.0,"(41.4993, -81.6944)","(37.09024, -95.712891)"

In [25]:
check_null(emission2017)

Columns with null values:
C40                                             173
Protocol column                                  78
Gases included                                  118
Total emissions (metric tonnes CO2e)             12
Total Scope 1 Emissions (metric tonnes CO2e)     56
Total Scope 2 Emissions (metric tonnes CO2e)     57
Comment                                         150
Increase/Decrease from last year                 20
Reason for increase/decrease in emissions        51
GDP                                              48
GDP Currency                                     45
GDP Year                                         44
GDP Source                                       51
Average annual temperature (in Celsius)​          6
​Average altitude (m)                            22
​Land area (in square km)                         1
dtype: int64

In [41]:
emission2017['C40'] = emission2017['C40'].apply(lambda x: convert_to_boolean(x))
emission2017.drop(columns=['Organization'], inplace=True)

emission2017

,Account number,City,Country,Region,C40,Access,Reporting year,Accounting year,Boundary,Protocol,...,Population year,GDP,GDP Currency,GDP Year,GDP Source,Average annual temperature (in Celsius)​,​Average altitude (m),​Land area (in square km),City Location,Country Location
0,49363,Nelson Mandela Bay,South Africa,Africa,False,Public,2017,2013-07-01 - 2014-06-30,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,...,2011,5.214700e+04,ZAR South African Rand,2010.0,Built Environment Performance Plan(BEPP),17.5,69.0,1950.0,"(-33.745241, 25.568108)","(-30.559482, 22.937506)"
1,31171,Madrid,Spain,Europe,False,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,Global Protocol for Community-Scale Greenhouse...,...,2016,1.293780e+11,EUR Euro,2015.0,Contabilidad Municipal Trimestral. Ciudad de M...,15.0,655.0,604.0,"(40.1076253, -3.3875673)","(40.463667, -3.74922)"
2,3417,New York City,USA,North America,False,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,Global Protocol for Community-Scale Greenhouse...,...,2016,1.558520e+12,USD US Dollar,2015.0,http://www.brookings.edu/research/reports2/201...,13.0,10.0,784.0,"(40.7127837, -74.0059413)","(37.09024, -95.712891)"
3,59537,"Denton, TX",USA,North America,False,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,U.S. Community Protocol for Accounting and Rep...,...,2015,NaN,NaN,NaN,NaN,18.2,192.0,227.8,"(33.214841, -97.133068)","(37.09024, -95.712891)"
4,35894,Montreal,Canada,North America,False,Public,2017,2013-01-01 - 2013-12-31,A metropolitan area,Global Protocol for Community-Scale Greenhouse...,...,2013,1.154128e+08,CAD Canadian Dollar,2013.0,Institut de la statistique du Québec,6.8,17.0,500.0,"(45.5086699, -73.5539925)","(56.130366, -106.346771)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
224,19233,Torres Vedras,Portugal,Europe,False,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,International Emissions Analysis Protocol (ICLEI),...,2011,NaN,NaN,NaN,NaN,15.0,75.0,407.0,"(38.763669, -9.30148)","(39.399872, -8.224454)"
225,60273,Extrema,Brazil,Latin America,False,Public,2017,2014-01-01 - 2014-12-31,Administrative boundary of a local government,Global Protocol for Community-Scale Greenhouse...,...,2016,4.676285e+09,BRL Brazilian Real,2014.0,IBGE,17.7,973.0,243.1,"(-22.840262, -46.328)","(-14.235004, -51.92528)"
226,31148,Amsterdam,Netherlands,Europe,False,Public,2017,2015-12-01 - 2016-12-31,Administrative boundary of a local government,Other,...,2016,6.450000e+10,EUR Euro,2016.0,https://public.tableau.com/profile/gemeente.am...,10.9,2.0,219.0,"(52.370216, 4.895168)","(52.132633, 5.291266)"
227,54119,Palo Alto,USA,North America,False,Public,2017,2016-01-01 - 2016-12-31,Administrative boundary of a local government,U.S. Community Protocol for Accounting and Rep...,...,2017,NaN,USD US Dollar,NaN,City GDP data is not available,15.0,7.0,67.0,"(37.4419, -122.143)","(37.09024, -95.712891)"
228,35859,Cleveland,USA,North America,False,Public,2017,2015-01-01 - 2015-12-31,Administrative boundary of a local government,Global Protocol for Community-Scale Greenhouse...,...,2010,1.284480e+11,USD US Dollar,2015.0,U.S. Bureau of Economic Analysis; U.S. Bureau ...,10.4,199.0,201.0,"(41.4993, -81.6944)","(37.09024, -95.712891)"

In [48]:
# Save the DataFrame to a CSV file
emission2017.to_csv('../DB/Data/new_2017_emissions.csv', index=False)

## Climate report 2023

In [37]:

report2023

,Questionnaire,Organization Number,Organization Name,City,Country/Area,CDP Region,C40,GCoM City,Access,Assessment attachment and/or direct link,Confirm attachment/link provided,Boundary of assessment relative to jurisdiction boundary,Year of publication or approval,Factors considered in assessment,Primary author(s) of assessment,Does the city have adaptation goal(s) and/or an adaptation plan?,Population,Population Year,City Location,Last update
0,Cities 2023,840926,Prefeitura de Serra Talhada,NaN,Brazil,Latin America,False,True,public,https://drive.google.com/file/d/19DMxxK532IQSL...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,Assessment considers vulnerable populations; A...,Dedicated team within jurisdiction; Relevant d...,Adaptation goal(s) and adaptation plan,92228,2023.0,NaN,02/07/2024 04:14:16 AM
1,Cities 2023,51075,City of Shenzhen,Shenzhen,China,East Asia,True,False,public,NaN,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,Assessment considers nature; Assessment consid...,Consultant; Dedicated team within jurisdiction...,Adaptation plan,17662000,2022.0,POINT (113.813 22.9175),02/07/2024 04:14:16 AM
2,Cities 2023,863190,Renca,NaN,Chile,Latin America,False,False,public,PLCC_Renca (08 Abril).pdf,The assessment has been attached,Same - covers entire jurisdiction and nothing ...,2019.0,A process has been established for prioritizin...,Question not applicable,Adaptation goal(s) and adaptation plan,162517,2022.0,NaN,02/07/2024 04:14:16 AM
3,Cities 2023,930366,Municipalidad Distrital de Yura,NaN,Peru,Latin America,False,True,public,https://sigrid.cenepred.gob.pe/sigridv3/docume...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,Identified hazards have been incorporated into...,Dedicated team within jurisdiction,Incomplete report,33346,2017.0,NaN,02/07/2024 04:14:16 AM
4,Cities 2023,60236,Trelleborg Municipality,Trelleborg,Sweden,Europe,False,True,public,https://moten.trelleborg.se/welcome-sv/namnder...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2018.0,A process has been established for prioritizin...,Dedicated team within jurisdiction,Adaptation goal(s) and adaptation plan,46649,2022.0,POINT (13.1569 55.3751),02/07/2024 04:14:16 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1365,Cities 2023,58871,"City of Salem, MA",Salem,United States of America,United States of America,False,True,public,https://www.salemma.gov/sites/g/files/vyhlif79...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2021.0,A process has been established to update the a...,Consultant,Adaptation goal(s) and adaptation plan,44480,2020.0,POINT (-70.8967 42.5195),02/07/2024 04:14:16 AM
1366,Cities 2023,55800,"City of Cambridge, MA","Cambridge, MA",United States of America,United States of America,False,True,public,ccpralewifepreparednessplan_cambridge.pdf,The assessment has been attached and can be ac...,Smaller - covers only part of the jurisdiction...,2017.0,Assessment considers nature; Assessment consid...,Dedicated team within jurisdiction; Relevant d...,Adaptation goal(s) and adaptation plan,118403,2020.0,POINT (-71.1057 42.3674),02/07/2024 04:14:16 AM
1367,Cities 2023,16581,"City of Seattle, WA",Seattle,United States of America,United States of America,True,True,public,https://your.kingcounty.gov/dnrp/climate/docum...,The assessment can be accessed (unrestricted) ...,Larger - covers the whole jurisdiction and adj...,2021.0,Assessment considers nature; Assessment consid...,Regional/ state/ provincial government,Adaptation goal(s) and adaptation plan,737015,2020.0,POINT (-122.332 47.6062),02/07/2024 04:14:16 AM
1368,Cities 2023,826450,Durham County Council,NaN,United Kingdom of Great Britain and Northern I...,Europe,False,True,public,Final PHSMT Climate and Health in County Durha...,The assessment has been attached,Same - covers entire jurisdiction and nothing ...,2023.0,A process has been established for prioritizin...,Dedicated team within jurisdiction; Relevant d...,Adaptation plan,522100,2021.0,NaN,02/07/2024 04:14:16 AM
1369,Cities 2023,924874,Municipio de San Luis,NaN,Argentina,Latin America,False,True,public,PLAC San Luis.pdf,The assessment has been attached,Same - covers entire jurisdiction and nothing ...,2022.0,A process has been established for prioritizin...,"Dedicated team within jurisdiction; Other, ple...",Adaptation goal(s) and adaptation plan,188498,2019.0,NaN,02/07/2024 04:14:16 AM

In [35]:
check_null(report2023)

Columns with null values:
City                                                        439
Assessment attachment and/or direct link                     37
Boundary of assessment relative to jurisdiction boundary     12
Year of publication or approval                              26
Factors considered in assessment                             51
Primary author(s) of assessment                              50
Population Year                                               8
City Location                                               570
dtype: int64

In [52]:
report2023.rename(columns={'C40 City': 'C40'}, inplace=True)
report2023.rename(columns={'Country/Area': 'Country'}, inplace=True)

report2023 = report2023.dropna(subset=["City"]) 
report2023.reset_index(drop=True, inplace=True)

report2023

,Questionnaire,Organization Number,Organization Name,City,Country,CDP Region,C40,GCoM City,Access,Assessment attachment and/or direct link,Confirm attachment/link provided,Boundary of assessment relative to jurisdiction boundary,Year of publication or approval,Factors considered in assessment,Primary author(s) of assessment,Does the city have adaptation goal(s) and/or an adaptation plan?,Population,Population Year,City Location,Last update
0,Cities 2023,51075,City of Shenzhen,Shenzhen,China,East Asia,True,False,public,NaN,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2022.0,Assessment considers nature; Assessment consid...,Consultant; Dedicated team within jurisdiction...,Adaptation plan,17662000,2022.0,POINT (113.813 22.9175),02/07/2024 04:14:16 AM
1,Cities 2023,60236,Trelleborg Municipality,Trelleborg,Sweden,Europe,False,True,public,https://moten.trelleborg.se/welcome-sv/namnder...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2018.0,A process has been established for prioritizin...,Dedicated team within jurisdiction,Adaptation goal(s) and adaptation plan,46649,2022.0,POINT (13.1569 55.3751),02/07/2024 04:14:16 AM
2,Cities 2023,54125,"City of Boise, ID",Boise,United States of America,United States of America,False,False,public,https://www.cityofboise.org/departments/public...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2016.0,Assessment considers water security,"Other, please specify: University of Idaho",Adaptation goal(s) and adaptation plan,236634,2022.0,NaN,02/07/2024 04:14:16 AM
3,Cities 2023,35857,"City of Cincinnati, OH",Cincinnati,United States of America,United States of America,False,True,public,https://www.hamiltoncountyohio.gov/emergency_m...,The assessment can be accessed (unrestricted) ...,Larger - covers the whole jurisdiction and adj...,2018.0,Assessment considers nature; Assessment consid...,Regional/ state/ provincial government,Adaptation goal(s) and adaptation plan,308935,2021.0,POINT (-84.512 39.1031),02/07/2024 04:14:16 AM
4,Cities 2023,850566,Prefeitura de Piraquara,Piraquara,Brazil,Latin America,False,False,public,http://sisvuclima.mma.gov.br/visualizar_indice/,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2017.0,Assessment considers nature; Identified hazard...,National/ central government,Adaptation goal(s),118730,2022.0,NaN,02/07/2024 04:14:16 AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
926,Cities 2023,35449,City of Zürich,Zürich,Switzerland,Europe,False,True,public,pr20230713_Umweltbericht 2022.pdf,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2023.0,A process has been established to update the a...,Dedicated team within jurisdiction; Relevant d...,Adaptation goal(s) and adaptation plan,443037,2022.0,POINT (8.53918 47.3686),02/07/2024 04:14:16 AM
927,Cities 2023,54034,"City of Grand Rapids, MI",Grand Rapids,United States of America,United States of America,False,True,public,https://www.grandrapidsmi.gov/files/assets/pub...,The assessment can be accessed (unrestricted) ...,Larger - covers the whole jurisdiction and adj...,2013.0,Assessment considers nature; Assessment consid...,Community group; Dedicated team within jurisdi...,Adaptation goal(s),199417,2020.0,NaN,02/07/2024 04:14:16 AM
928,Cities 2023,58871,"City of Salem, MA",Salem,United States of America,United States of America,False,True,public,https://www.salemma.gov/sites/g/files/vyhlif79...,The assessment can be accessed (unrestricted) ...,Same - covers entire jurisdiction and nothing ...,2021.0,A process has been established to update the a...,Consultant,Adaptation goal(s) and adaptation plan,44480,2020.0,POINT (-70.8967 42.5195),02/07/2024 04:14:16 AM
929,Cities 2023,55800,"City of Cambridge, MA","Cambridge, MA",United States of America,United States of America,False,True,public,ccpralewifepreparednessplan_cambridge.pdf,The assessment has been attached and can be ac...,Smaller - covers only part of the jurisdiction...,2017.0,Assessment considers nature; Assessment consid...,Dedicated team within jurisdiction; Relevant d...,Adaptation goal(s) and adaptation plan,118403,2020.0,POINT (-71.1057 42.3674),02/07/2024 04:14:16 AM
930,Cities 2023,16581,"City of Seattle, WA",Seattle,United States of America,United States of America,True,True,public,https://your.kingcounty.gov/dnrp/climate/docum...,The assessment can be accessed (unrestricted) ...,Larger - covers the whole jurisdiction and adj...,2021.0,Assessment considers nature; Assessment consid...,Regional/ state/ provincial government,Adaptation goal(s) and adaptation plan,737015,2020.0,POINT (-122.332 47.6062),02/07/2024 04:14:16 AM

In [53]:
# Save the DataFrame to a CSV file
report2023.to_csv('../DB/Data/new_2023_report.csv', index=False)